"""gen_vectors.py -- regenerate sim/vectors/*.hex from b3pow_ref.py
and ref/vectors/consensus_vectors.json (consumed by the C++ unit tests).

The .hex files bridge between the Python reference (this tree's
authoritative spec) and the SystemVerilog testbenches in ../sim/tb/.
The JSON file is the bridge to the C++ consensus port in
b3chain/src/crypto/b3pow_scratch.{h,cpp}; the corresponding unit test
is b3chain/src/test/b3pow_scratch_tests.cpp.

Each .hex file is a plain ASCII file with one record per line:

    <name>: <hex bytes ...>

Comments start with '#'.  Blank lines are ignored.  The testbenches
parse them with $fscanf / Verilator C++ harness.

Run:

    cd b3chain/contrib/miner/b3miner-rtl/ref
    python gen_vectors.py --out ../sim/vectors
    # consensus JSON is emitted to ./vectors/consensus_vectors.json by
    # default; override with --consensus-out.

Re-running is idempotent.  CI verifies that the checked-in RTL produces
the same hashes the freshly-generated vectors expect, and that the C++
port produces the same `expected_pow_hash` bytes as the JSON.
"""
from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path
from typing import List

import b3pow_ref as ref


# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
def _hexline(name: str, *blobs: bytes) -> str:
    return f"{name}: " + " ".join(b.hex() for b in blobs)


def _write(out: Path, lines: List[str]) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join([
        "# auto-generated by ref/gen_vectors.py -- do not edit",
        f"# b3pow_ref SPEC_VERSION = {ref.SPEC_VERSION:#010x}",
        *lines,
        "",
    ])
    out.write_text(text)
    print(f"wrote {out} ({len(lines)} records)")


# ----------------------------------------------------------------------------
# Vector generators
# ----------------------------------------------------------------------------
def gen_blake3_compress(out_dir: Path) -> None:
    """Vectors for rtl/blake3_compress.sv.

    For each test case:
        cv:        8 × 32-bit LE words
        block:     16 × 32-bit LE words
        counter:   8 bytes LE
        block_len: 4 bytes LE
        flags:     4 bytes LE
        out:       16 × 32-bit LE words (post-compress)
    """
    lines = []
    test_cases = [
        # (label, cv_bytes, block_bytes, counter, blen, flags)
        ("zero_cv_zero_block",
         bytes(32), bytes(64), 0, 0, ref.FLAG_CHUNK_START | ref.FLAG_CHUNK_END | ref.FLAG_ROOT),
        ("iv_cv_byte_block",
         ref.pack_le_words(list(ref.BLAKE3_IV)),
         bytes(range(64)), 1, 64, ref.FLAG_CHUNK_START | ref.FLAG_CHUNK_END | ref.FLAG_ROOT),
        ("random_cv_one_block",
         bytes.fromhex(
             "0123456789ABCDEF" "FEDCBA9876543210"
             "DEADBEEFCAFEBABE" "0BADF00DC0FFEE00"),
         bytes.fromhex("AA" * 64), 2, 64, ref.FLAG_CHUNK_END | ref.FLAG_ROOT),
    ]
    for label, cv_bytes, block_bytes, counter, blen, flags in test_cases:
        cv = ref.le_words(cv_bytes)
        block = ref.le_words(block_bytes)
        out = ref.blake3_compress_full(cv, block, counter, blen, flags)
        lines.append(_hexline(
            label,
            ref.pack_le_words(cv),
            ref.pack_le_words(block),
            struct.pack("<Q", counter),
            struct.pack("<I", blen),
            struct.pack("<I", flags),
            ref.pack_le_words(out),
        ))
    _write(out_dir / "blake3_compress.hex", lines)


def gen_blake3_xof(out_dir: Path) -> None:
    lines = []
    cases = [
        ("empty", b"", 64),
        ("ascii_abc", b"abc", 32),
        ("64_bytes_ramp", bytes(range(64)), 128),
        ("prev_hash_zero", bytes(32) + struct.pack("<I", 0), 64),
    ]
    for label, inp, olen in cases:
        out = ref.blake3_xof(inp, olen)
        lines.append(_hexline(label, inp, struct.pack("<I", olen), out))
    _write(out_dir / "blake3_xof.hex", lines)


def gen_scratch_init(out_dir: Path) -> None:
    """Vectors for rtl/scratch_init.sv.

    Dumps the first 4 blocks (256 bytes) of the scratchpad for each
    prev_block_hash case so the TB doesn't have to load 1 MB.
    """
    lines = []
    cases = [
        ("zero", bytes(32)),
        ("one_bit", bytes([0x80]) + bytes(31)),
        ("random", bytes.fromhex(
            "DEADBEEFCAFEBABE" "0BADF00DC0FFEE00"
            "ABCDEF0123456789" "FEDCBA9876543210")),
    ]
    for label, prev in cases:
        pad = ref.init_scratchpad(prev)
        first_blocks = bytes(pad[: 4 * ref.BLOCK_BYTES])
        lines.append(_hexline(label, prev, first_blocks))
    _write(out_dir / "scratch_init.hex", lines)


def gen_mixing_one_iter(out_dir: Path) -> None:
    """One mixing iteration (the inner-loop step the RTL mixing_core does)."""
    lines = []
    cases = [
        ("zero", [bytes(32)] * ref.LANES, [bytes(64)] * ref.LANES),
        ("iv",
         [ref.pack_le_words(list(ref.BLAKE3_IV))] * ref.LANES,
         [bytes(range(64))] * ref.LANES),
        ("random",
         [bytes(range(L * 8, L * 8 + 32)) for L in range(ref.LANES)],
         [bytes(range(64 + L, 128 + L)) for L in range(ref.LANES)]),
    ]
    for label, lanes_in, blocks_in in cases:
        new_lanes, new_blocks = ref.mix_step(lanes_in, blocks_in)
        lines.append(_hexline(
            label,
            *lanes_in,
            *blocks_in,
            *new_lanes,
            *new_blocks,
        ))
    _write(out_dir / "mixing_one_iter.hex", lines)


def gen_full_hash(out_dir: Path) -> None:
    """End-to-end vectors for rtl/b3miner_top.sv.

    Format per line:
        label: header(80) prev_hash(32) pow_hash(32) lanes_final(256)
    """
    lines = []
    cases = [
        ("zero_header_zero_prev", bytes(80), bytes(32)),
        ("ones_header_zero_prev", bytes([0xFF]) * 80, bytes(32)),
        ("ramp_header_random_prev",
         bytes(range(80)),
         bytes.fromhex("DEADBEEFCAFEBABE" "0BADF00DC0FFEE00"
                       "ABCDEF0123456789" "FEDCBA9876543210")),
        ("nonced",
         ref.header_with_nonce(bytes(range(80)), 0x12345678),
         bytes(32)),
    ]
    for label, header, prev in cases:
        result = ref.b3pow_scratch(header, prev)
        lines.append(_hexline(
            label,
            header,
            prev,
            result.pow_hash,
            ref.serialise_lanes(result.lanes_final),
        ))
    _write(out_dir / "full_hash.hex", lines)


def gen_regfile_trace(out_dir: Path) -> None:
    """SPI command/response trace used by tb_regfile.sv and tb_b3miner_top.sv.

    Each line is a 40-bit SPI transaction in the format the firmware emits:
        op: <wr|rd> reg=0xXX data=0xXXXXXXXX  -> expected_miso=0xXXXXXXXX
    """
    lines = []
    lines.append("# Boot trace: firmware reads REG_ID then writes seed/job/start.")
    lines.append(_hexline("read_id_expect_magic",
                         struct.pack("<B", 0x00),       # cmd = rd, reg=0x00
                         struct.pack("<I", 0x00000000),  # MOSI data (don't care)
                         struct.pack("<I", ref.REG_ID_MAGIC)))  # expected MISO

    # 8 × seed writes
    seed = b"".join(struct.pack("<I", 0xCAFE_0000 | i) for i in range(8))
    for i in range(8):
        lines.append(_hexline(f"wr_seed_{i}",
                             struct.pack("<B", 0x80 | (0x40 // 4 + i)),  # wr, REG_SEED_BASE+i
                             seed[i*4:(i+1)*4],
                             struct.pack("<I", 0)))

    # 8 × prev_hash writes (all zero)
    for i in range(8):
        lines.append(_hexline(f"wr_prev_{i}",
                             struct.pack("<B", 0x80 | (0x60 // 4 + i)),
                             struct.pack("<I", 0),
                             struct.pack("<I", 0)))

    # nonce range + epoch
    lines.append(_hexline("wr_nonce_start",
                         struct.pack("<B", 0x80 | (0x80 // 4)),
                         struct.pack("<I", 0x00000000),
                         struct.pack("<I", 0)))
    lines.append(_hexline("wr_nonce_end",
                         struct.pack("<B", 0x80 | (0x84 // 4)),
                         struct.pack("<I", 0x000000FF),
                         struct.pack("<I", 0)))
    lines.append(_hexline("wr_job_epoch",
                         struct.pack("<B", 0x80 | (0x1C // 4)),
                         struct.pack("<I", 0x00000001),
                         struct.pack("<I", 0)))

    # SCRATCH_INIT then START_JOB
    lines.append(_hexline("wr_ctrl_scratch_init",
                         struct.pack("<B", 0x80 | (0x08 // 4)),
                         struct.pack("<I", 1 << 2),
                         struct.pack("<I", 0)))
    lines.append(_hexline("wr_ctrl_start_job",
                         struct.pack("<B", 0x80 | (0x08 // 4)),
                         struct.pack("<I", 1 << 0),
                         struct.pack("<I", 0)))

    _write(out_dir / "regfile_trace.hex", lines)


# ----------------------------------------------------------------------------
# Consensus vectors -- byte-for-byte oracle for b3chain/src/crypto/b3pow_scratch.cpp
#
# Schema (v1):
#
# {
#   "schema_version": 1,
#   "spec_version":   "0x00010100",
#   "entries": [
#     {
#       "name":                  "<unique label>",
#       "header_hex":            "<160 hex chars, 80 bytes LE-on-wire>",
#       "prev_block_hash_hex":   "<64 hex chars, 32 bytes>",
#       "expected_pow_hash_hex": "<64 hex chars, 32 bytes>",
#       "nbits_hex":             "0xNNNNNNNN",
#       "expected_check_pow":    true | false,
#       "notes":                 "<free text, optional>"
#     },
#     ...
#   ]
# }
#
# `expected_check_pow` is computed against `nbits_hex` using the same
# little-endian-uint256 vs compact-target comparison src/pow.cpp does.
# ----------------------------------------------------------------------------
CONSENSUS_SCHEMA_VERSION = 1

# Mainnet / testnet / signet powLimit from kernel/chainparams.cpp.
# Post-F-6 fix (M-13), the floor is tightened 4x from the original
# 0x1e01ffff to 0x1d7fffff:
#   0x0000007fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
# Compact-encoded:
#   target = 0x007fffff << (8 * (29 - 3))   ==> nBits = 0x1d7fffff
MAINNET_POW_LIMIT_NBITS = 0x1d7fffff
# Regtest powLimit:
#   0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
#   nBits = 0x207fffff (any hash passes -- size=0x20, mantissa=0x7fffff)
REGTEST_POW_LIMIT_NBITS = 0x207fffff


def _u256_le_int(buf: bytes) -> int:
    return int.from_bytes(buf, byteorder="little")


def _nbits_to_target(nbits: int) -> int:
    # Mirror of src/pow.cpp::DeriveTarget for valid-range nBits.
    size = (nbits >> 24) & 0xFF
    word = nbits & 0x007FFFFF
    return word >> (8 * (3 - size)) if size <= 3 else word << (8 * (size - 3))


def _build_header(
    version: int = 1,
    prev_hash: bytes = bytes(32),
    merkle_root: bytes = bytes(32),
    n_time: int = 1739145600,
    n_bits: int = MAINNET_POW_LIMIT_NBITS,
    nonce: int = 0,
) -> bytes:
    return (
        struct.pack("<I", version)
        + prev_hash
        + merkle_root
        + struct.pack("<I", n_time)
        + struct.pack("<I", n_bits)
        + struct.pack("<I", nonce)
    )


def _emit_entry(
    name: str,
    header: bytes,
    prev_hash: bytes,
    nbits: int,
    notes: str = "",
) -> dict:
    res = ref.b3pow_scratch(header, prev_hash)
    target = _nbits_to_target(nbits)
    pass_ = _u256_le_int(res.pow_hash) <= target
    return {
        "name": name,
        "header_hex": header.hex(),
        "prev_block_hash_hex": prev_hash.hex(),
        "expected_pow_hash_hex": res.pow_hash.hex(),
        "nbits_hex": f"0x{nbits:08x}",
        "expected_check_pow": pass_,
        "notes": notes,
    }


def gen_consensus_vectors(out_path: Path) -> None:
    """Build the JSON file consumed by the C++ b3pow_scratch_tests.cpp.

    These vectors must match byte-for-byte between the Python reference
    and the C++ port; any drift is a consensus break.
    """
    entries: List[dict] = []

    # ------------------------------------------------------------------
    # 1. genesis_mainnet_template -- post-F-6 fix mainnet genesis header
    #    parameters.  From kernel/chainparams.cpp:
    #      CreateGenesisBlock(1739145600, 89222440, 0x1d7fffff, 1, 50*COIN)
    #    merkle_root is determined by the coinbase tx; we use a
    #    placeholder zero here -- the vector is a "schema locker" that
    #    asserts the JSON parses and the C++ port byte-matches the
    #    Python ref, not that it matches the on-chain genesis bytes.
    # ------------------------------------------------------------------
    entries.append(_emit_entry(
        name="genesis_mainnet_template",
        header=_build_header(
            version=1, prev_hash=bytes(32), merkle_root=bytes(32),
            n_time=1739145600, n_bits=MAINNET_POW_LIMIT_NBITS, nonce=89222440,
        ),
        prev_hash=bytes(32),
        nbits=MAINNET_POW_LIMIT_NBITS,
        notes="Mainnet genesis template post-F-6 fix (zero merkle_root "
              "placeholder; the real on-chain merkle is in chainparams.cpp). "
              "Locks the JSON schema.",
    ))

    # ------------------------------------------------------------------
    # 2. genesis_regtest -- regtest accepts any hash (powLimit ≈ 2^255-1)
    # ------------------------------------------------------------------
    entries.append(_emit_entry(
        name="genesis_regtest",
        header=_build_header(
            version=1, prev_hash=bytes(32), merkle_root=bytes(32),
            n_time=1739145602, n_bits=REGTEST_POW_LIMIT_NBITS, nonce=0,
        ),
        prev_hash=bytes(32),
        nbits=REGTEST_POW_LIMIT_NBITS,
        notes="Regtest genesis template (nonce=0).  Regtest powLimit "
              "(0x207fffff) accepts ~50% of random hashes, so the "
              "expected_check_pow flag is whatever the comparator gives.",
    ))

    # ------------------------------------------------------------------
    # 3. mainnet_target_boundary_pass / _fail
    #
    # We pick a synthetic nBits where the compact target is small enough
    # that some headers fail and some pass.  The exact header bytes are
    # chosen so the resulting pow_hash brackets the target.  Both entries
    # share `prev_hash = 0` to share the pad init in the C++ test.
    #
    # We deliberately don't search for a nonce -- searching takes minutes
    # in Python (~1.3 ms/hash × 2^16 = 80 s on a slow box).  Instead we
    # use the loose mainnet powLimit, where every hash passes, and a
    # very tight synthetic nBits where every hash fails.  The C++ test
    # asserts the *boolean* `expected_check_pow` for both, exercising
    # both branches of the target comparator.
    # ------------------------------------------------------------------
    tight_nbits = 0x03000001  # target = 1 -- effectively unreachable
    entries.append(_emit_entry(
        name="mainnet_target_loose_pass",
        header=_build_header(nonce=0xDEAD_BEEF),
        prev_hash=bytes(32),
        nbits=MAINNET_POW_LIMIT_NBITS,
        notes="Mainnet powLimit (0x1d7fffff, post-F-6 fix).  "
              "expected_check_pow is computed from the actual pow_hash "
              "-- the C++ port must agree byte-for-byte on the hash *and* "
              "on the boolean.",
    ))
    entries.append(_emit_entry(
        name="mainnet_target_tight_fail",
        header=_build_header(nonce=0xDEAD_BEEF),
        prev_hash=bytes(32),
        nbits=tight_nbits,
        notes="Synthetic tight target (target=1) -- expected to fail "
              "with overwhelming probability.",
    ))

    # ------------------------------------------------------------------
    # 4. nontrivial_prev -- confirms the pad init differs when
    #    prev_block_hash changes, by comparing this entry's
    #    expected_pow_hash to one of the prev=0 entries with the same
    #    header bytes (the C++ test does that comparison too).
    # ------------------------------------------------------------------
    entries.append(_emit_entry(
        name="nontrivial_prev",
        header=_build_header(nonce=0xDEAD_BEEF),
        prev_hash=bytes.fromhex(
            "DEADBEEFCAFEBABE" "0BADF00DC0FFEE00"
            "ABCDEF0123456789" "FEDCBA9876543210"
        ),
        nbits=MAINNET_POW_LIMIT_NBITS,
        notes="Same header as mainnet_target_loose_pass but non-zero "
              "prev_block_hash; pow_hash MUST differ.",
    ))

    # ------------------------------------------------------------------
    # 5. cache_correctness_pair -- two headers sharing prev_block_hash
    #    but with different nonces.  The C++ test feeds both through the
    #    B3PoWCache and asserts (a) the second is a cache hit, (b) the
    #    two pow_hashes are byte-for-byte what we compute here, (c) the
    #    cached pad bytes are bitwise identical between calls.
    # ------------------------------------------------------------------
    shared_prev = bytes.fromhex(
        "0102030405060708" "090A0B0C0D0E0F10"
        "1112131415161718" "191A1B1C1D1E1F20"
    )
    entries.append(_emit_entry(
        name="cache_pair_nonce_0",
        header=_build_header(prev_hash=shared_prev, nonce=0),
        prev_hash=shared_prev,
        nbits=MAINNET_POW_LIMIT_NBITS,
        notes="Cache-pair member 1 (nonce=0) -- shares prev_block_hash "
              "with cache_pair_nonce_1.",
    ))
    entries.append(_emit_entry(
        name="cache_pair_nonce_1",
        header=_build_header(prev_hash=shared_prev, nonce=1),
        prev_hash=shared_prev,
        nbits=MAINNET_POW_LIMIT_NBITS,
        notes="Cache-pair member 2 (nonce=1) -- C++ test asserts this "
              "is served from the cache after member 1.",
    ))

    payload = {
        "schema_version": CONSENSUS_SCHEMA_VERSION,
        "spec_version": f"0x{ref.SPEC_VERSION:08x}",
        "entries": entries,
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {out_path} ({len(entries)} entries)")


# ----------------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------------
GENERATORS = [
    gen_blake3_compress,
    gen_blake3_xof,
    gen_scratch_init,
    gen_mixing_one_iter,
    gen_full_hash,
    gen_regfile_trace,
]


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--out", "-o", default="../sim/vectors",
        help="Output directory for the .hex testbench vectors "
             "(default: ../sim/vectors)",
    )
    p.add_argument(
        "--consensus-out", default="vectors/consensus_vectors.json",
        help="Output path for the consensus JSON file consumed by the "
             "C++ unit tests (default: vectors/consensus_vectors.json, "
             "relative to ref/)",
    )
    args = p.parse_args()
    out_dir = Path(args.out).resolve()
    for fn in GENERATORS:
        fn(out_dir)
    gen_consensus_vectors(Path(args.consensus_out).resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
