#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the b3chain network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
};

static const uint8_t chainparams_seed_signet[] = {
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0xa6,0x58,0x04,0xfa,0x48,0x65,
    0x01,0x04,0x97,0x9e,0x01,0x16,0x48,0x65,
    0x01,0x04,0x97,0x9e,0x01,0x3c,0x48,0x65,
};

static const uint8_t chainparams_seed_testnet4[] = {
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
